#pragma config(Sensor, S2,     GyroSensor,     sensorEV3_Gyro)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          thirdMotor,    tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
    Program: This program uses the gyro sensor as throttle control.
    Authors: Joshua Stanley, Jack McCarthy
    Date:20/03/2024

*/

task throttle();

task main()
{
    ///starting the gyro task
    tartTask(throttle);
    resetGyro(GyroSensor);

        while(true)
        {
              ///robots speeds depends on the gyro's movement
              setMotorSync(leftMotor, rightMotor, 0, (getGyroDegrees(GyroSensor) / 2));
                 
        }
           
           
}
     
    task throttle()
    {
    ///infinite loop to continue moviung the gyro sensor
      while(true){
            sleep(1);
            ///moving motor back and forth
            resetMotorEncoder(thirdMotor);
            setMotorTarget(thirdMotor, 90, 5);
            waitUntilMotorStop(thirdMotor);
           
            resetMotorEncoder(thirdMotor);
            setMotorTarget(thirdMotor, -90, 5);
            waitUntilMotorStop(thirdMotor);
           
      }
}